DROP TABLE STBL_BRANCH;
CREATE TABLE STBL_BRANCH (
BRCD VARCHAR(3) NOT NULL,
DES VARCHAR(100),
PRIMARY KEY (BRCD));

DROP TABLE STBL_MARGIN;
CREATE TABLE STBL_MARGIN (
SHAPE VARCHAR(100) NOT NULL,
SIZE VARCHAR(100) NOT NULL,
CLARITY VARCHAR(100) NOT NULL,
COLOR VARCHAR(100) NOT NULL,
MARGIN DECIMAL(18,2),
PRIMARY KEY(SHAPE,SIZE,CLARITY,COLOR));